### ISSUE TITLE
terraform-google-kubernetes-engine autogen broken in CFT cft/developer-tools 1.3.10+ 

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/cloud-foundation-toolkit#1208]
Starting with CFT v1.3.10 autogen(https://github.com/apeabody/terraform-google-kubernetes-engine/blob/c9361a8206b91983e6121cee36074d0871f27f03/Makefile#L87) isn't working

```
Traceback (most recent call last):
  File "/usr/local/bin/generate_modules.py", line 22, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
```

**Comment by bharathkkb** [comment]
Nothing stood out to me btw commits and GHA logs have expired. We don't seem to pin jinja https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/install_dependencies.sh#L73

**Comment by apeabody** [comment]
Thanks @bharathkkb - I'll dig into it later, but I think it might be related to a mismatch between jinja2 and markupsafe versions: https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0
